sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

matrix:
  include:
    # linux
    - os: linux
      env: NODE_VERSION="4"     # abi 46
    - os: linux
      env: NODE_VERSION="5.1.1"     # abi 47
    - os: linux
      env: NODE_VERSION="6"     # abi 48
    # os x x86
    - os: osx
      env: NODE_VERSION="4"
    - os: osx
      env: NODE_VERSION="5.1.1"
    - os: osx
      env: NODE_VERSION="6"
    # osx ia32
    - os: osx
      env: NODE_VERSION="4" TARGET_ARCH="ia32"
    - os: osx
      env: NODE_VERSION="5.1.1" TARGET_ARCH="ia32"
    - os: osx
      env: NODE_VERSION="6" TARGET_ARCH="ia32"

before_install:
  - rm -rf ~/.nvm/ && git clone --depth 1 "https://github.com/creationix/nvm.git" ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - if [[ $NODE_VERSION == "0.10" ]]; then
      npm -g install npm@latest-2;
    fi
  - export PATH="./node_modules/.bin/:$PATH"

install:
  - export CXX=g++-4.8
  - $CXX --version
  - npm install

script:
  - if [[ -z "$TARGET_ARCH" ]]; then
      node-pre-gyp rebuild package testpackage --build-from-source;
      npm test;
    else
      node-pre-gyp rebuild package testpackage --build-from-source --target_arch=$TARGET_ARCH;
    fi

git:
  depth: 10

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+(?:-[a-z0-9.-]+)?$/

before_deploy:
  - export RELEASE_NODE_FILE=$(find build/stage -name '*.tar.gz')
  - echo "Deploying $RELEASE_NODE_FILE to GitHub"

deploy:
  provider: releases
  api_key:
    secure: 5b9cyZ1AyHDqW6XkmFQ7vZCv5ftOk0TZAreU+Rkk6BbRSrCb6Rhno+7m+dCnUDCXsXXg0n708LWptOQP8mb/9WVEeIooDTytjKY7FHJJGjF1wsyxbym8gIHwRxP3O/MQ3JiAabeewpmHrUrtolBqYRo4QReDCrUWcp4hzvy/GKHe0nCxR+W0KP5DvwsD2hh+g9mrZhD90HalawPvQ04ykp8VDx/afJ43bUAdfWQO8gJNwK/RHZXpml463bVcGbwEYSJhiZ6o07xBF9betcxGUsV2s3TFua4x/nN1Dc5voLI6u7E8PRkzzObZtEI2aQkTaC1FfaUTQHsRNZA4LTL55B4c0YbyWYHSNGEolpI58zhV3p+84OV9JX8c2efN5DMZ+wAM2cPFq6EiGYHdUjhXEqtZlheMMWxBrDsIk/oQCxg9ETF/owR45Sizj/Uqi5BNIdEkeGmKN1xxmdH34vyV65U5PVqckdvmM9rTwN0/EZKCCBh8z0LfrdMqkSa8sYXgMv7a0E2iXyJ2lHc00riQXhFj6oMhpepOQ47nTuRKTvXpEGCGA8jG7KrRsEnZ1AQ736fSqp3CElnEkxvvVErnaC7KFsQgsml8Su3dMmU2gCRpXpjBUgcfoovAJ9eqO17zl3/dppHKo8oGFKlzsdfEBKZCM3awAO3l6MT3G4nulLo=
  file: "$RELEASE_NODE_FILE"
  skip_cleanup: true
  on:
    repo: hansonw/ctags-prebuilt
    tags: true
